### ISSUE TITLE
Repeater functionality incorrect?

### ISSUE THREAD

**Issue by DanTulovsky** [askft/go-behave#1]
Sorry if I misunderstand how this is supposed to work. It seems that the Repeater is supposed to repeat its children after they return Success or Failure.  But if a child is running, the Repeater should allow it to finish running.  If this is the intended behavior, then repeater.go, at the top of Tick() should have something like:

	status := core.Update(d.Child, ctx)

	// Continue if child is running
	if status == core.StatusRunning {
		return core.StatusRunning
	
Which makes the demo code works correctly.  Without this, it just runs for one tick and exits, even though the 700ms child hasn't yet completed.

Thanks
Dan

**Comment by askft** [comment]
Hi Dan,

You are indeed correct – thank you very much!

I have committed a fix [here](https://github.com/askft/go-behave/commit/d0125cecfabcd5442168d6f1c04cf45cd75746b6).
